config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    render :index, locals: { products: Product.all }
  end

  def show
    render :show, locals: { product: Product.find(params[:id]) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand centered" href="<%= products_path %>">DISHY</a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyWebshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<div>
  <% products.find_in_batches(batch_size: 4).each do |product_batch| %>
    <div class="row" style="margin:1%">
      <% product_batch.each do |product| %>
        <div class="col-md-3">
          <a href="<%= product_path(product.id) %>">
            <div class="card" style="width: 20rem;">
              <img class="card-img-top" src="http://bit.ly/2gYpuNe" style="max-height:100%; max-width:100%">
              <div class="card-block">
                <h4 class="card-title"><%= product.name %></h4>
                <p class="card-text"><%= product.description.truncate(100) %></p>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <img class="card-img-top" src="http://bit.ly/2gYpuNe">
  </div>

  <div class="col-md-6">
    <div class="card-block">
      <h4 class="card-title">
        <div class="row">
          <div class="col-md-10 mb10"><%= product.name %></div>
          <div class="col-md-2 pull-right">$<%= product.price %></div>
        </div>
      </h4>

      <p class="card-text"><%= product.description %></p>
    </div>
  </div>
</div>